In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.colors import Normalize
import os
import math
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
import matplotlib.gridspec as gridspec

In [2]:
from aux_func_States import *

from functions_for_plotting import *

In [3]:
mpl.rcParams['xtick.labelsize'] = 20
mpl.rcParams['ytick.labelsize'] = 20
mpl.rcParams.update({'font.size': 20})

In [4]:
og = pd.read_csv("../coupledWReg_Ccode/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")

In [5]:
reduced=np.unique(og,axis=0)
colL = og.columns
print colL
u,mz,Z,ms,u3,S,A,Rmt,Rnox,h,mh=0,1,2,3,4,5,6,7,8,9,10

Index([u'u', u'mz', u'Z', u'ms', u'u3', u'S', u'A', u'Rmt', u'Rnox', u'h',
       u'mh'],
      dtype='object')


In [6]:
for key in og.columns:
    print key ,np.unique(og[key].values)

u [ 1265.014555 12389.217608 19098.53803 ]
mz [ 62.206072 301.843678 990.401024]
Z [  5968.97567   45516.30189  742309.632898]
ms [451.154065 458.464267 458.511561]
u3 [ 8177.938943 16908.61767  16993.323703]
S [196610.267902 196878.362674 238329.654592]
A [ 68.715505 327.638356 436.489801]
Rmt [  8.372377 128.975137 138.265605]
Rnox [ 1.646083  8.949039 30.507473]
h [ 26.664078 292.17448  479.867662]
mh [ 31.108091 340.870227 559.845606]


In [7]:
labs={0:'u',1:'mz',2:'Z',3:'ms',4:'u3',5:'S'}
for k1 in [u,mz,Z,ms,u3,S]:
    for k2 in [Z]:#u,mz,Z,ms,u3,S]:
        print labs[k1],labs[k2],np.unique(reduced[:,k1]/reduced[:,k2])
        print (np.unique(reduced[:,k1]/reduced[:,k2])-np.mean((reduced[:,k1]/reduced[:,k2])))/np.std(reduced[:,k1]/reduced[:,k2])
        print np.median(np.unique(reduced[:,k1]/reduced[:,k2]))
        print np.std(np.unique(reduced[:,k1]/reduced[:,k2])),'\n'


u Z [1.70416023e-03 2.72192975e-01 3.19963409e+00]
[-0.79844961 -0.61164545  1.41009506]
0.27219297468281206
1.4479806438839946 

mz Z [0.00133422 0.00663155 0.01042157]
[-1.286575    0.13481569  1.15175931]
0.0066315510150510605
0.0037268680302862366 

Z Z [1.]
[nan]
1.0
0.0 

ms Z [0.00060777 0.01007253 0.07681579]
[-0.84203991 -0.56296511  1.40500501]
0.010072528917397074
0.03391477187710298 

u3 Z [0.01101688 0.37148487 2.84694136]
[-0.84525487 -0.55928812  1.40454299]
0.37148487394391877
1.2605241240420548 

S Z [ 0.32106502  4.32544725 32.93869481]
[-0.84046239 -0.56476486  1.40522725]
4.325447246347017
14.52454928006867 



/home/madeline/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in divide
  """


In [8]:
labs={0:'u',1:'mz',2:'Z',3:'ms',4:'u3',5:'S',10:'mh',9:'h',8:'Rnox',7:'Rmt',6:'A'}
for k1 in [A,Rmt,Rnox,h,mh]:
    for k2 in [A,Rmt,Rnox,h,mh]:
        print labs[k1],labs[k2],np.unique(reduced[:,k1]/reduced[:,k2])
        print (np.unique(reduced[:,k1]/reduced[:,k2])-np.mean((reduced[:,k1]/reduced[:,k2])))/np.std(reduced[:,k1]/reduced[:,k2])
        print np.median(np.unique(reduced[:,k1]/reduced[:,k2]))
        print np.std(np.unique(reduced[:,k1]/reduced[:,k2])),'\n'


A A [1.]
[nan]
1.0
0.0 

A Rmt [2.36963022 3.38429415 8.20740693]
[-0.89690097 -0.49847954  1.39538052]
3.384294145002536
2.546710224461121 

A Rnox [  2.2524155   36.61156868 265.16876792]
[-0.84920625 -0.55475205  1.4039583 ]
36.6115686835201
116.68759483658438 

A h [ 0.14319678  1.1213791  16.36995665]
[-0.77191513 -0.64025405  1.41216918]
1.1213791019667427
7.42954831711917 

A mh [ 0.1227401   0.96118209 14.03139142]
[-0.77191513 -0.64025405  1.41216918]
0.9611820864601355
6.368184272035835 

Rmt A [0.12184116 0.29548259 0.42200677]
[-1.28356757  0.12764304  1.15592454]
0.29548259021062445
0.1230443042500673 

Rmt Rmt [1.]
[nan]
1.0
0.0 

Rmt Rnox [ 0.27443692 15.45032992 78.35275439]
[-0.91960924 -0.47064641  1.39025566]
15.450329918106291
33.80211431660022 

Rmt h [0.01744726 0.47322958 4.83703719]
[-0.80940514 -0.59961186  1.40901701]
0.4732295750128485
2.17253056597056 

Rmt mh [0.0149548  0.40562535 4.14603188]
[-0.80940514 -0.59961186  1.40901701]
0.4056253496143563
1.86216

/home/madeline/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in divide
  """


In [9]:
u,ms
mz,S
u3,Z

k1,k2=u,ms
print labs[k1],labs[k2],np.unique(reduced[:,k1]/reduced[:,k2])
print (np.unique(reduced[:,k1]/reduced[:,k2])-np.mean((reduced[:,k1]/reduced[:,k2])))/np.std(reduced[:,k1]/reduced[:,k2])
print np.median(np.unique(reduced[:,k1]/reduced[:,k2]))
print np.std(np.unique(reduced[:,k1]/reduced[:,k2])),'\n'

k1,k2=mz,S
print labs[k1],labs[k2],np.unique(reduced[:,k1]/reduced[:,k2])
print (np.unique(reduced[:,k1]/reduced[:,k2])-np.mean((reduced[:,k1]/reduced[:,k2])))/np.std(reduced[:,k1]/reduced[:,k2])
print np.median(np.unique(reduced[:,k1]/reduced[:,k2]))
print np.std(np.unique(reduced[:,k1]/reduced[:,k2])),'\n'

k1,k2=Z,u3
print labs[k1],labs[k2],np.unique(reduced[:,k1]/reduced[:,k2])
print (np.unique(reduced[:,k1]/reduced[:,k2])-np.mean((reduced[:,k1]/reduced[:,k2])))/np.std(reduced[:,k1]/reduced[:,k2])
print np.median(np.unique(reduced[:,k1]/reduced[:,k2]))
print np.std(np.unique(reduced[:,k1]/reduced[:,k2])),'\n'

u ms [ 2.80395247 27.0233004  41.65334019]
[-1.31225578  0.19952239  1.11273339]
27.023300396059
16.020437655995078 

mz S [0.00031639 0.00153315 0.00415559]
[-1.05201968 -0.29248936  1.34450904]
0.001533148050910024
0.0016019837697168924 

Z u3 [ 0.35125416  2.69189964 90.76976951]
[-0.73473443 -0.6791145   1.41384893]
2.6918996442126066
42.0828517438979 



In [10]:

k1,k2=Rmt,Rnox
print labs[k1],labs[k2],np.unique(reduced[:,k1]/reduced[:,k2])
print (np.unique(reduced[:,k1]/reduced[:,k2])-np.mean((reduced[:,k1]/reduced[:,k2])))/np.std(reduced[:,k1]/reduced[:,k2])
print np.median(np.unique(reduced[:,k1]/reduced[:,k2]))
print np.std(np.unique(reduced[:,k1]/reduced[:,k2])),'\n'

k1,k2=h,A
print labs[k1],labs[k2],np.unique(reduced[:,k1]/reduced[:,k2])
print (np.unique(reduced[:,k1]/reduced[:,k2])-np.mean((reduced[:,k1]/reduced[:,k2])))/np.std(reduced[:,k1]/reduced[:,k2])
print np.median(np.unique(reduced[:,k1]/reduced[:,k2]))
print np.std(np.unique(reduced[:,k1]/reduced[:,k2])),'\n'


Rmt Rnox [ 0.27443692 15.45032992 78.35275439]
[-0.91960924 -0.47064641  1.39025566]
15.450329918106291
33.80211431660022 

h A [0.06108752 0.89175908 6.98339715]
[-0.83740716 -0.56824219  1.40564934]
0.8917590832985378
3.0861057865313923 



In [11]:
df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3m/EMT_MR_comp_u3m_0_000_1000_res.txt")

arr= np.unique(df,axis=0)

k1,k2=Rmt,Rnox
print labs[k1],labs[k2],np.unique(arr[:,k1]/arr[:,k2])
print (np.unique(arr[:,k1]/arr[:,k2])-np.mean((arr[:,k1]/arr[:,k2])))/np.std(arr[:,k1]/arr[:,k2])
k1,k2=h,A
print labs[k1],labs[k2],np.unique(arr[:,k1]/arr[:,k2])
print (np.unique(arr[:,k1]/arr[:,k2])-np.mean((arr[:,k1]/arr[:,k2])))/np.std(arr[:,k1]/arr[:,k2])
k1,k2=Z,u3
print labs[k1],labs[k2],np.unique(arr[:,k1]/arr[:,k2])
print (np.unique(arr[:,k1]/arr[:,k2])-np.mean((arr[:,k1]/arr[:,k2])))/np.std(arr[:,k1]/arr[:,k2])
k1,k2=mz,S
print labs[k1],labs[k2],np.unique(arr[:,k1]/arr[:,k2])
print (np.unique(arr[:,k1]/arr[:,k2])-np.mean((arr[:,k1]/arr[:,k2])))/np.std(arr[:,k1]/arr[:,k2])
k1,k2=u,ms
print labs[k1],labs[k2],np.unique(arr[:,k1]/arr[:,k2])
print (np.unique(arr[:,k1]/arr[:,k2])-np.mean((arr[:,k1]/arr[:,k2])))/np.std(arr[:,k1]/arr[:,k2])


Rmt Rnox [  0.47422581  12.57991261  12.58576473  19.77698594 113.8572522 ]
[-0.75674885 -0.46481805 -0.46467692 -0.29125933  1.97750315]
h A [0.05702773 0.9992748  3.07949986 3.10027744 6.28670738]
[-1.23317444 -0.79429174  0.17464182  0.18431966  1.6685047 ]
Z u3 [ 0.35125416  2.69189964 90.76976951]
[-1.25133263 -1.19780619  0.81637961]
mz S [0.00031639 0.00153315 0.00415559]
[-1.56358063 -0.81658761  0.79338941]
u ms [ 2.80395247 27.0233004  41.65334019]
[-0.78217553  0.71966061  1.62686598]


In [12]:
og = pd.read_csv("../coupledWReg_Ccode/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")
red_og_emt = np.unique(og.values[:,:6],axis=0)
red_og_mr = np.unique(og.values[:,6:],axis=0)

uvals = og['u'].values
emtStates = []
for i in range(len(red_og_emt)):
    if red_og_emt[i,0]==np.min(uvals):
        emtStates+=['M']
    elif red_og_emt[i,0]==np.max(uvals):
        emtStates+=['E']
    else:
        emtStates+=['EM']
        
hvals = og['h'].values
mrStates=[]
for i in range(len(red_og_mr)):
    if red_og_mr[i,3]==np.min(hvals):
        mrStates+=['O']
    elif red_og_mr[i,3]==np.max(hvals):
        mrStates+=['W']
    else:
        mrStates+=['WO']
        
        
ratios_emt=[]
ratios_mr=[]
emt_ksets=[[u,mz],[mz,u],[u,ms],[u3,ms],[u3,mz],[S,Z]]
for i in range(len(red_og_emt)):
    ratios_emt+=[[]]
    for [k1,k2] in emt_ksets:
        ratios_emt[i] =[(red_og_emt[i][k1-6]/red_og_emt[i][k2-6]-np.mean(og.values[:,k1]/og.values[:,k2])/np.std(og.values[:,k1]/og.values[:,k2]))]

mr_ksets=[[A,Rnox],[A,Rmt],[h,Rnox],[h,Rmt],[A,h],[h,A]]
for i in range(len(red_og_mr)):
    ratios_mr+=[[]]
    for [k1,k2] in mr_ksets:
        ratios_mr[i] =[(red_og_mr[i][k1-6]/red_og_mr[i][k2-6]-np.mean(og.values[:,k1]/og.values[:,k2])/np.std(og.values[:,k1]/og.values[:,k2]))]

    
ratios_emt = np.array(ratios_emt)
ratios_mr = np.array(ratios_mr)

In [13]:
print mrStates
print red_og_mr
print emtStates
print red_og_emt

['W', 'WO', 'O']
[[ 68.715505   8.372377  30.507473 479.867662 559.845606]
 [327.638356 138.265605   8.949039 292.17448  340.870227]
 [436.489801 128.975137   1.646083  26.664078  31.108091]]
['M', 'EM', 'E']
[[1.26501455e+03 9.90401024e+02 7.42309633e+05 4.51154065e+02
  8.17793894e+03 2.38329655e+05]
 [1.23892176e+04 3.01843678e+02 4.55163019e+04 4.58464267e+02
  1.69086177e+04 1.96878363e+05]
 [1.90985380e+04 6.22060720e+01 5.96897567e+03 4.58511561e+02
  1.69933237e+04 1.96610268e+05]]


In [14]:
df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3m/EMT_MR_comp_u3m_0_000_1000_res.txt")

mean_emt = [np.mean(df.values[:,u]/df.values[:,ms]),np.mean(df.values[:,mz]/df.values[:,S]),np.mean(df.values[:,Z]/df.values[:,u3])]
std_emt = [np.std(df.values[:,u]/df.values[:,ms]),np.std(df.values[:,mz]/df.values[:,S]),np.std(df.values[:,Z]/df.values[:,u3])]
mean_mr = [np.mean(df.values[:,Rmt]/df.values[:,Rnox]),np.mean(df.values[:,h]/df.values[:,A])]
std_mr = [np.std(df.values[:,Rmt]/df.values[:,Rnox]),]

In [15]:
results={'E/O':0,'E/WO':0,'E/W':0,
             'M/O':0,'M/WO':0,'M/W':0,
             'EM/O':0,'EM/WO':0,'EM/W':0,
             'E':0,'EM':0,'M':0,
             'O':0,'WO':0,'W':0}

states=[]
for i in range(len(df)):
    tmp_emt
    for [k1,k2] in emt_ksets:
        tmp_emt+=[(df.values[i,k1]/df.values[i,k2]-np.mean(df.values[:,k1]/df.values[:,k2]))/np.std(df.values[:,k1]/df.values[:,k2])]
    tmp_mr=[]
    for [k1,k2] in mr_ksets:
        tmp_mr+=[(df.values[i,k1]/df.values[i,k2]-np.mean(df.values[:,k1]/df.values[:,k2]))/np.std(df.values[:,k1]/df.values[:,k2])]
            
    tmp_mr=np.array(tmp_mr)
    tmp_emt=np.array(tmp_emt)
    
    d_emt = np.sum((tmp_emt-ratios_emt)**2,axis=1)
    loc_emt = np.argwhere(np.min(d_emt)==d_emt)[:,0][0]
    #print emtStates[loc_emt]
    
    d_mr = np.sum((tmp_mr-ratios_mr)**2,axis=1)
    print tmp_mr
    loc_mr = np.argwhere(np.min(d_mr)==d_mr)[:,0][0]
    #print mrStates[loc_mr]
    
    states+=[mrStates[loc_mr]]
    results[emtStates[loc_emt]+"/"+mrStates[loc_mr]]+=1


NameError: name 'tmp_emt' is not defined

In [ ]:
results

In [ ]:
ratios_mr

In [ ]:
## u,ms         mz, S             Z,u3
## Rmt, Rnox       h,A

plt.plot(og.values[:,u]/og.values[:,ms],'ro',markersize=22)
plt.plot(df.values[:,u]/df.values[:,ms],'*')
plt.show()

plt.plot(og.values[:,mz]/og.values[:,S],'r*',markersize=22)
plt.plot(df.values[:,mz]/df.values[:,S],'*')
plt.show()
plt.plot(og.values[:,Z]/og.values[:,u3],'r*',markersize=22)
plt.plot(df.values[:,Z]/df.values[:,u3],'*')
plt.show()
plt.plot(og.values[:,Rmt]/og.values[:,Rnox],'r*',markersize=22)
plt.plot(df.values[:,Rmt]/df.values[:,Rnox],'*')
plt.show()
plt.plot(og.values[:,h]/og.values[:,A],'r*',markersize=22)
plt.plot(df.values[:,h]/df.values[:,A],'*')
plt.show()

In [ ]:
## u,ms         mz, S             Z,u3
## Rmt, Rnox       h,A

plt.plot((og.values[:,u]/og.values[:,ms]-np.mean(og.values[:,u]/og.values[:,ms]))/np.std(og.values[:,u]/og.values[:,ms]),'ro',markersize=22)
plt.plot((df.values[:,u]/df.values[:,ms]-np.mean(df.values[:,u]/df.values[:,ms]))/np.std(df.values[:,u]/df.values[:,ms]),'*')
plt.show()

plt.plot((og.values[:,mz]/og.values[:,S]-np.mean(og.values[:,mz]/og.values[:,S]))/np.std(og.values[:,mz]/og.values[:,S]),'r*',markersize=22)
plt.plot((df.values[:,mz]/df.values[:,S]-np.mean(df.values[:,mz]/df.values[:,S]))/np.std(df.values[:,mz]/df.values[:,S]),'*')
plt.show()
plt.plot((og.values[:,Z]/og.values[:,u3]-np.mean(og.values[:,Z]/og.values[:,u3]))/np.std(og.values[:,Z]/og.values[:,u3]),'r*',markersize=22)
plt.plot((df.values[:,Z]/df.values[:,u3]-np.mean(df.values[:,Z]/df.values[:,u3]))/np.std(df.values[:,Z]/df.values[:,u3]),'*')
plt.show()
plt.plot((og.values[:,Rmt]/og.values[:,Rnox]-np.mean(og.values[:,Rmt]/og.values[:,Rnox]))/np.std(og.values[:,Rmt]/og.values[:,Rnox]),'r*',markersize=22)
plt.plot((df.values[:,Rmt]/df.values[:,Rnox]-np.mean(df.values[:,Rmt]/df.values[:,Rnox]))/np.std(df.values[:,Rmt]/df.values[:,Rnox]),'*')
plt.show()
plt.plot((og.values[:,h]/og.values[:,A]-np.mean(og.values[:,h]/og.values[:,A]))/np.std(og.values[:,h]/og.values[:,A]),'r*',markersize=22)
plt.plot((df.values[:,h]/df.values[:,A]-np.mean(df.values[:,h]/df.values[:,A]))/np.std(df.values[:,h]/df.values[:,A]),'*')
plt.show()

In [ ]:
df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3m/EMT_MR_comp_u3m_0_600_1000_res.txt")
for k1 in [A,h]:
    for k2 in [Rmt,Rnox,A]:
        plt.title(labs[k1]+" "+labs[k2])
        plt.plot((og.values[:,k1]/og.values[:,k2]-np.mean(og.values[:,k1]/og.values[:,k2]))/np.std(og.values[:,k1]/og.values[:,k2]),'ro',markersize=10)
        plt.plot((df.values[:,k1]/df.values[:,k2]-np.mean(df.values[:,k1]/df.values[:,k2]))/np.std(df.values[:,k1]/df.values[:,k2]),'o')
        plt.show()

In [ ]:
for key in df.columns:
    plt.plot(og[key],'ro',markersize=22)
    plt.plot(df[key],'*')
    plt.title(key)
    plt.show()

In [ ]:
df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3m/EMT_MR_comp_u3m_0_000_1000_res.txt")

mean_emt = [np.mean(df.values[:,u]/df.values[:,ms]),np.mean(df.values[:,mz]/df.values[:,S]),np.mean(df.values[:,Z]/df.values[:,u3])]
std_emt = [np.std(df.values[:,u]/df.values[:,ms]),np.std(df.values[:,mz]/df.values[:,S]),np.std(df.values[:,Z]/df.values[:,u3])]
mean_mr = [np.mean(df.values[:,Rmt]/df.values[:,Rnox]),np.mean(df.values[:,h]/df.values[:,A])]
std_mr = [np.std(df.values[:,Rmt]/df.values[:,Rnox]),np.std(df.values[:,h]/df.values[:,A])]

## Entropy?? - choose lowest entropy?


In [ ]:
og = pd.read_csv("../coupledWReg_Ccode/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")
red_og_emt = np.unique(og.values[:,:6],axis=0)
red_og_mr = np.unique(og.values[:,6:],axis=0)

uvals = og['u'].values
emtStates = []
for i in range(len(red_og_emt)):
    if red_og_emt[i,0]==np.min(uvals):
        emtStates+=['M']
    elif red_og_emt[i,0]==np.max(uvals):
        emtStates+=['E']
    else:
        emtStates+=['EM']
        
hvals = og['h'].values
mrStates=[]
for i in range(len(red_og_mr)):
    if red_og_mr[i,3]==np.min(hvals):
        mrStates+=['O']
    elif red_og_mr[i,3]==np.max(hvals):
        mrStates+=['W']
    else:
        mrStates+=['WO']
        
      

In [ ]:
uniques = np.unique(og.values,axis=0)
print uniques[:,u]
print uniques[:,h]
states=['M/W','M/WO','M/O','EM/W','EM/WO','EM/O','E/W','E/WO','E/O']

In [ ]:
for el in ['900','800','600','200','000']:
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3n/EMT_MR_comp_u3n_0_"+el+"_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        #print df['u'].values[i], df['h'].values[i]
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
            #print tmp
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        #print states[loc[0]],'\n'
        results[states[loc[0]]]+=1

    print results

In [ ]:
for el in ['900','800','600','200','000']:
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_HS/EMT_MR_comp_HS_1_00_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        #print df['u'].values[i], df['h'].values[i]
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
            #print tmp
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        #print states[loc[0]],'\n'
        results[states[loc[0]]]+=1

    print results

In [ ]:
uniques = np.unique(og.values,axis=0)
print uniques[:,u]
print uniques[:,h]
states=['M/W','M/WO','M/O','EM/W','EM/WO','EM/O','E/W','E/WO','E/O']

In [ ]:
for el in [0]:
    df = pd.read_csv("../coupledWReg_Ccode/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0,
                'E':0,'EM':0,'M':0,'W':0,'WO':0,'O':0}

    for i in range(len(df)):
        #print df['u'].values[i], df['h'].values[i]
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
            #print tmp
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        #print states[loc[0]],'\n'
        results[states[loc[0]]]+=1
        tmpA,tmpB  =states[loc[0]].split("/")
        results[tmpA]+=1
        results[tmpB]+=1

    print results

In [ ]:
results_og={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0,
                'E':0,'EM':0,'M':0,'W':0,'WO':0,'O':0}

for i in range(len(og.values)):
    
    dist = np.sum((og.values[i]-uniques)**2,axis=1)
    loc = np.argwhere(np.min(dist)==dist)[:,0][0]
    results_og[states[loc]]+=1
    tmpA,tmpB  =states[loc].split("/")
    results_og[tmpA]+=1
    results_og[tmpB]+=1


In [ ]:
results

In [ ]:
results_og

In [ ]:
for i in range(len(og)):
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(og.columns)):
                prob=og.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
            #print tmp
        locI = np.argwhere(np.min(tmpS)==tmpS)[:,0][0]

        dist = np.sum((og.values[i]-uniques)**2,axis=1)
        locD = np.argwhere(np.min(dist)==dist)[:,0][0]

        if locI!=locD:
            print locI,locD

In [ ]:
df = pd.read_csv("data/crosstalk_comparison.txt")
inds = np.argwhere(df['nics']==1000)[:,0]
print df.columns[10:-1]
print df.values[inds[4],10:-1]

## Check entropy for "all"

In [ ]:
for el in range(10):
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3m/EMT_MR_comp_u3m_0_"+str(el)+"00_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        results[states[loc[0]]]+=1

    print results

In [ ]:
for el in range(10):
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3n/EMT_MR_comp_u3n_0_"+str(el)+"00_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        results[states[loc[0]]]+=1

    print results
    

In [ ]:
for el in range(10):
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_iHu/EMT_MR_comp_Hu_0_"+str(el)+"00_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        results[states[loc[0]]]+=1

    print results

In [ ]:
for el in range(10):
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_AZ/EMT_MR_comp_AZ_0_"+str(el)+"0_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        results[states[loc[0]]]+=1

    print results

In [ ]:
for el in range(10):
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_AS/EMT_MR_comp_AS_0_"+str(el)+"0_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        results[states[loc[0]]]+=1

    print results

In [ ]:
for el in range(1,10):
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_Au/EMT_MR_comp_Au_"+str(el)+"_00_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        results[states[loc[0]]]+=1

    print results

In [ ]:
for el in range(1,10):
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_HS/EMT_MR_comp_HS_"+str(el)+"_00_1000_res.txt")

    results={'E/O':0,'E/WO':0,'E/W':0,
                 'M/O':0,'M/WO':0,'M/W':0,
                 'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        tmpS =[]
        for k in range(len(uniques)):
            tmp=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
            tmpS+=[tmp]
        loc = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        results[states[loc[0]]]+=1

    print results

# Entropy vs info gain

In [ ]:
og = pd.read_csv("../coupledWReg_Ccode/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")
red_og_emt = np.unique(og.values[:,:6],axis=0)
red_og_mr = np.unique(og.values[:,6:],axis=0)
u,mz,Z,ms,u3,S,A,Rmt,Rnox,h,mh=0,1,2,3,4,5,6,7,8,9,10

uvals = og['u'].values
emtStates = []
for i in range(len(red_og_emt)):
    if red_og_emt[i,0]==np.min(uvals):
        emtStates+=['M']
    elif red_og_emt[i,0]==np.max(uvals):
        emtStates+=['E']
    else:
        emtStates+=['EM']
        
hvals = og['h'].values
mrStates=[]
for i in range(len(red_og_mr)):
    if red_og_mr[i,3]==np.min(hvals):
        mrStates+=['O']
    elif red_og_mr[i,3]==np.max(hvals):
        mrStates+=['W']
    else:
        mrStates+=['WO']
        
      

In [ ]:
uniques = np.unique(og.values,axis=0)
print uniques[:,u]
print uniques[:,h]
states=['M/W','M/WO','M/O','EM/W','EM/WO','EM/O','E/W','E/WO','E/O']

In [ ]:
for el in ['900','800','600','200','000']:
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3n/EMT_MR_comp_u3n_0_"+el+"_1000_res.txt")

    results1={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}
    results2={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}
    results3={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}
    results4={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}

    for i in range(len(df)):
        #print df['u'].values[i], df['h'].values[i]
        tmpS =[]
        tmpS2 =[]
        tmpS3=[]
        tmpS4=[]
        for k in range(len(uniques)):
            tmp=0
            tmp2=0
            tmp3=0
            tmp4=0
            for j in range(len(df.columns)):
                prob=df.values[i,j]/uniques[k,j]
                tmp+=np.log10(prob)**2
                tmp3+=np.log10(prob)
                tmp2+=prob*np.log10(prob)
                tmp4+=prob*np.log10(prob)**2
            tmpS+=[tmp]
            tmpS2+=[np.abs(tmp2)]
            tmpS3+=[np.abs(tmp3)]
            tmpS4+=[tmp4]
            #print tmp
        loc1 = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        loc2 = np.argwhere(np.min(tmpS2)==tmpS2)[:,0]
        loc3 = np.argwhere(np.min(tmpS3)==tmpS3)[:,0]
        loc4 = np.argwhere(np.min(tmpS4)==tmpS4)[:,0]
        #print states[loc[0]],'\n'
        results1[states[loc1[0]]]+=1
        results2[states[loc2[0]]]+=1
        results3[states[loc3[0]]]+=1
        results4[states[loc4[0]]]+=1

    print results1
   # print results2    
    #print results3    
    print results4 ,'\n'   

# Entropy vs info gain - on normalized states


In [ ]:
og = pd.read_csv("../coupledWReg_Ccode/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")
red_og_emt = np.unique(og.values[:,:6],axis=0)
red_og_mr = np.unique(og.values[:,6:],axis=0)
u,mz,Z,ms,u3,S,A,Rmt,Rnox,h,mh=0,1,2,3,4,5,6,7,8,9,10

uvals = og['u'].values
emtStates = []
for i in range(len(red_og_emt)):
    if red_og_emt[i,0]==np.min(uvals):
        emtStates+=['M']
    elif red_og_emt[i,0]==np.max(uvals):
        emtStates+=['E']
    else:
        emtStates+=['EM']
        
hvals = og['h'].values
mrStates=[]
for i in range(len(red_og_mr)):
    if red_og_mr[i,3]==np.min(hvals):
        mrStates+=['O']
    elif red_og_mr[i,3]==np.max(hvals):
        mrStates+=['W']
    else:
        mrStates+=['WO']
        
      

In [ ]:
uniques = np.unique(og.values,axis=0)
print uniques[:,u]
print uniques[:,h]
states=['M/W','M/WO','M/O','EM/W','EM/WO','EM/O','E/W','E/WO','E/O']

mean_og = np.mean(og.values,axis=0)
std_og = np.std(og.values,axis=0)

In [ ]:
for el in ['900','800','600','200','000']:
    df = pd.read_csv("../coupledWReg_Ccode/singles/crosstalk_u3n/EMT_MR_comp_u3n_0_"+el+"_1000_res.txt")

    results1={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}
    results2={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}
    results3={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}
    results4={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}
    results5={'E/O':0,'E/WO':0,'E/W':0, 'M/O':0,'M/WO':0,'M/W':0,'EM/O':0,'EM/WO':0,'EM/W':0}
    
    full_setp = np.append(df.values,og.values,axis=0)
    mean_df = np.mean(full_setp,axis=0)
    std_df = np.std(full_setp,axis=0)

    for i in range(len(df)):
        #print df['u'].values[i], df['h'].values[i]
        tmpS =[]
        tmpS2 =[]
        tmpS3=[]
        tmpS4=[]
        tmpS5=[]
        
        for k in range(len(uniques)):
            tmp=0
            tmp2=0
            tmp3=0
            tmp4=0
            tmp5=0
            for j in range(len(df.columns)):
                prob=((df.values[i,j]-mean_df)/std_df)/((uniques[k,j]-mean_og)/std_og)
                prob2=((df.values[i,j]))/((uniques[k,j]))
                #print prob
                #tmp+=np.log10(prob)**2
                #tmp3+=np.log10(prob)
                #tmp2+=prob*np.log10(prob)
                #tmp4+=prob*np.log10(prob)**2
                tmp+=prob
                tmp2+=prob**2
                tmp3+=np.abs(prob)*np.log10(prob**2)
                tmp4+=prob*np.log10(np.abs(prob))
                tmp5+=np.log10(prob2)**2
            tmpS+=[tmp]
            tmpS2+=[np.abs(tmp2)]
            tmpS3+=[np.abs(tmp3)]
            tmpS4+=[tmp4]
            tmpS5+=[tmp5]
            #print tmp
        loc1 = np.argwhere(np.min(tmpS)==tmpS)[:,0]
        loc2 = np.argwhere(np.min(tmpS2)==tmpS2)[:,0]
        loc3 = np.argwhere(np.min(tmpS3)==tmpS3)[:,0]
        loc4 = np.argwhere(np.min(tmpS4)==tmpS4)[:,0]
        loc5 = np.argwhere(np.min(tmpS5)==tmpS5)[:,0]
        #print states[loc[0]],'\n'
        results1[states[loc1[0]]]+=1
        results2[states[loc2[0]]]+=1
        results3[states[loc3[0]]]+=1
        results4[states[loc4[0]]]+=1
        results5[states[loc5[0]]]+=1

    print results1
    print results2    
    print results3    
    print results4    
    print results5 ,'\n'   

In [6]:
###################


In [33]:
dfnoem = pd.read_csv("../normalCells_coupled/noPartialEMT/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")
dfnowo = pd.read_csv("../normalCells_coupled/normal_metabolic/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")
dfog = pd.read_csv("../coupledWReg_Ccode/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")
dfnohh = pd.read_csv("../normalCells_coupled/bothModified/crosstalk_comparison/EMT_MR_comp_0_1000_res.txt")
tmp = pd.read_csv("../normalCells_coupled/bothModified/crosstalk_Hu_u3m_input/EMT_MR_Hu_0_0_u3m_0_0_input_0_1000_res.txt")

In [34]:
for key in dfnoem:
    print key,np.unique(dfnohh[key])
    print np.unique(tmp[key])
    #print np.unique(dfnowo[key])   
    print np.unique(dfog[key])

u [ 1557.823875 33948.268289]
[5501.072522]
[ 1265.014555 12389.217608 19098.53803 ]
mz [ 100.758154 1673.108608]
[149.117726]
[ 62.206072 301.843678 990.401024]
Z [   6359.333974 1177805.879679]
[51167.306045]
[  5968.97567   45516.30189  742309.632898]
ms [447.195943 458.511449]
[121.133997]
[451.154065 458.464267 458.511561]
u3 [ 5601.839277 16993.122321]
[23427.569649]
[ 8177.938943 16908.61767  16993.323703]
S [196610.90323  259606.812165]
[47333.534543]
[196610.267902 196878.362674 238329.654592]
A [ 79.079849 384.998313]
[255.312321]
[ 68.715505 327.638356 436.489801]
Rmt [ 12.77508  104.151456]
[531.060134]
[  8.372377 128.975137 138.265605]
Rnox [ 1.632091 23.62897 ]
[31.191541]
[ 1.646083  8.949039 30.507473]
h [ 19.916108 327.834101]
[904.57312]
[ 26.664078 292.17448  479.867662]
mh [ 29.210291 480.823349]
[1326.707243]
[ 31.108091 340.870227 559.845606]


In [40]:
hh= getStates(dfnohh)
em= getStates(dfnoem)
wo= getStates(dfnowo)

print hh['E'],hh['M'],hh['W'],hh['O'],hh['WO'],hh['EM']
print wo['E'],wo['M'],wo['W'],wo['O'],wo['WO']
print em['E'],em['M'],em['W'],em['O'],em['EM']
print getStates(tmp,noHH='noHH')

578 422 415 585 0 0
19 295 415 585 0
578 422 394 138 0
{'EM': 0, 'E': 1000, 'WO': 1000, 'M': 0, 'M/W': 0, 'EM/WO': 0, 'M/O': 0, 'O': 0, 'W': 0, 'M/WO': 0, 'EM/W': 0, 'E/O': 0, 'E/WO': 1000, 'EM/O': 0, 'E/W': 0}


In [41]:
res = pd.read_csv("data/noHH_crosstalk_Hu_u3m_input.txt")

In [42]:
inds = np.argwhere(res['INPUT']==0)[:,0]
inds2 = np.argwhere(res['U3M']==0)[:,0]
inds = np.intersect1d(inds,inds2)

In [43]:
for i in range(len(inds)):
    print res['INPUT'].values[inds[i]], res['U3M'].values[inds[i]],res['HU'].values[inds[i]],res['E'].values[inds[i]]    , res['EM'].values[inds[i]] , res['M'].values[inds[i]],   res['W'].values[inds[i]]  , res['O'].values[inds[i]] ,res['WO'].values[inds[i]]    

0.0 0.0 0.8 1000 0 0 0 0 1000
0.0 0.0 0.9 1000 0 0 0 0 1000
0.0 0.0 1.0 1000 0 0 0 0 1000
0.0 0.0 0.5 1000 0 0 0 0 1000
0.0 0.0 0.1 1000 0 0 0 0 1000
0.0 0.0 0.4 1000 0 0 0 0 1000
0.0 0.0 0.2 1000 0 0 0 0 1000
0.0 0.0 0.0 0 1000 0 0 0 1000
0.0 0.0 0.3 1000 0 0 0 0 1000
0.0 0.0 0.7 1000 0 0 0 0 1000
0.0 0.0 0.6 1000 0 0 0 0 1000
