In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.colors import Normalize
import os
import math
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
import matplotlib.gridspec as gridspec
import time


['data/PSF_crosstalk_Hu_u3m_input.txt' 'data/crosstalk_all.txt'
 'data/crosstalk_u3m_iHu_input.txt' 'data/noEM_crosstalk_Hu_input_u3m.txt'
 'data/noHH_crosstalk_Hu_u3m_input.txt'
 'data/noWO_crosstalk_Hu_input_u3m.txt']


In [13]:
df = pd.read_csv("onlyHH_files.txt")
print np.unique(df['filen'])

for filen in np.unique(df['filen']):
    print filen
    inds = np.argwhere(df['filen']==filen)[:,0]
    print df.columns
    print df.values[inds,3:],'\n'

['data/PSF_crosstalk_Hu_u3m_input.txt' 'data/crosstalk_all.txt'
 'data/crosstalk_u3m_iHu_input.txt' 'data/noEM_crosstalk_Hu_input_u3m.txt'
 'data/noHH_crosstalk_Hu_u3m_input.txt'
 'data/noWO_crosstalk_Hu_input_u3m.txt']
data/PSF_crosstalk_Hu_u3m_input.txt
Index([u'filen', u'amount', u'percentDiff', u'AS', u'AZ', u'AU', u'HS', u'HU',
       u'INPUT', u'U3M', u'U3N', u'UH', u'UHV'],
      dtype='object')
[[1.0 1.0 1.0 ... 1.0 1.0 0]
 [1.0 1.0 1.0 ... 1.0 1.0 0]
 [1.0 1.0 1.0 ... 1.0 1.0 0]
 ...
 [1.0 1.0 1.0 ... 1.0 1.0 0]
 [1.0 1.0 1.0 ... 1.0 1.0 0]
 [1.0 1.0 1.0 ... 1.0 1.0 0]] 

data/crosstalk_all.txt
Index([u'filen', u'amount', u'percentDiff', u'AS', u'AZ', u'AU', u'HS', u'HU',
       u'INPUT', u'U3M', u'U3N', u'UH', u'UHV'],
      dtype='object')
[[0.95 0.96 1.1 1.1 0.1 20000.0 0.1 0.2 2.857125567554786 302]
 [0.95 0.96 1.1 1.1 0.1 20000.0 0.0 0.1 0.8655015881732077 310]
 [0.95 0.95 1.1 1.1 0.1 20000.0 0.0 0.2 2.880649529453062 302]
 [0.95 0.95 1.1 1.1 0.1 20000.0 0.0 0.1 1.8832549

In [14]:
df = pd.read_csv("upreg_files.txt")
print np.unique(df['filen'])

for filen in np.unique(df['filen']):
    print filen
    inds = np.argwhere(df['filen']==filen)[:,0]
    print df.columns
    print df.values[inds,3:],'\n'

['data/PSF_crosstalk_AS_Hu.txt' 'data/PSF_crosstalk_Au_HS.txt'
 'data/PSF_crosstalk_HS.txt' 'data/PSF_crosstalk_Hu.txt'
 'data/PSF_crosstalk_Hu_u3m_input.txt' 'data/crosstalk_AS.txt'
 'data/crosstalk_AS_AZ_Au_HS_Hu_input.txt'
 'data/crosstalk_AS_Au_Hu_input.txt' 'data/crosstalk_AS_Au_Hu_u3m.txt'
 'data/crosstalk_AS_HS.txt' 'data/crosstalk_AS_HS_input.txt'
 'data/crosstalk_AS_HS_u3m.txt' 'data/crosstalk_AS_HS_u3m_input.txt'
 'data/crosstalk_AS_Hu.txt' 'data/crosstalk_AS_Hu_u3m.txt'
 'data/crosstalk_AS_input.txt' 'data/crosstalk_AS_u3m.txt'
 'data/crosstalk_AS_u3m_input.txt' 'data/crosstalk_AS_u3n.txt'
 'data/crosstalk_AS_uh.txt' 'data/crosstalk_AZ.txt'
 'data/crosstalk_AZ_Au.txt' 'data/crosstalk_AZ_HS.txt'
 'data/crosstalk_AZ_Hu.txt' 'data/crosstalk_AZ_input.txt'
 'data/crosstalk_AZ_u3m.txt' 'data/crosstalk_AZ_u3n.txt'
 'data/crosstalk_Au.txt' 'data/crosstalk_Au_HS_u3m.txt'
 'data/crosstalk_Au_Hu_input.txt' 'data/crosstalk_Au_input.txt'
 'data/crosstalk_Au_u3m.txt' 'data/crosstalk_Au_u3

[[1.0 1.0 1.0 ... 1.0 1.0 0]
 [1.0 1.0 1.0 ... 1.0 1.0 0]
 [1.0 1.0 1.0 ... 1.0 1.0 0]
 ...
 [1.0 1.0 1.0 ... 1.0 1.0 0]
 [1.0 1.0 1.0 ... 1.0 1.0 0]
 [1.0 1.0 1.0 ... 1.0 1.0 0]] 

data/crosstalk_u3m_input.txt
Index([u'filen', u'amount', u'percentDiff', u'AS', u'AZ', u'AU', u'HS', u'HU',
       u'INPUT', u'U3M', u'U3N', u'UH', u'UHV'],
      dtype='object')
[[1.0 1.0 1.0 1.0 1.0 50000.0 0.3 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 60000.0 0.6 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 60000.0 0.28 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 50000.0 0.25 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 60000.0 0.9 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 50000.0 0.5 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 50000.0 0.28 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 50000.0 0.1 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 60000.0 0.9 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 60000.0 0.23 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 60000.0 0.29 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 50000.0 0.21 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 50000.0 0.9 1.0 1.0 0]
 [1.0 1.0 1.0 1.0 1.0 50000.0 0.22 1.0 1.0 0]
 [